spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:local
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop


logging:
  level:
    root:  info
    org.h2: trace
    org.springframework.jdbc : trace